### ISSUE TITLE
開発環境・言語の選定

### ISSUE THREAD

**Issue by taishi-matsumura** [sunday-programmers/NTR-Ass#1]
何で作ろう？

**Comment by taishi-matsumura** [comment]
[@ITの記事](http://www.atmarkit.co.jp/ait/articles/1509/15/news162.html)を見てるとSwiftで作れそうな気がしてきたので、Swiftで。
加えて、C++やDirectXの練習としてWindows版も作ってみましょう。

**Comment by masami-sugao** [comment]
それで問題ないと思います。
